# Generated by Django 5.1.1 on 2024-10-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('total_slots', models.IntegerField()),
                ('available_slots', models.IntegerField()),
                ('charging_slots', models.IntegerField()),
                ('charging_types', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
